### PR TITLE
get_foreign_keys only for tables, not aliases

### PR DESCRIPTION
**Pull request by mdobrzanski**
This is in reference to https://github.com/ibmdb/python-ibmdbsa/issues/20

The fix is to return foreign keys only between tables by making a join SQL and filtering tables by type = 'T'.

### CODE REVIEW

**Comment by asierra01** [comment]
When I have a chance will do a test with your code....I would image this filter will fix the duplicate fk...that include the (wrong) alias tables

**Comment by CJ-Wright** [comment]
This fixed the issue with the DB2 sample DB for me

**Comment by amukherjee28** [comment]
Changing the query for get_foreign_keys  to check where the foreign key table is of type table helps to distinguish alias from table.

Current new query

```
SELECT "SYSIBM"."SQLFOREIGNKEYS"."FK_NAME", "SYSIBM"."SQLFOREIGNKEYS"."FKTABLE_SCHEM", "SYSIBM"."SQLFOREIGNKEYS"."FKTABLE_NAME", "SYSIBM"."SQLFOREIGNKEYS"."FKCOLUMN_NAME", "SYSIBM"."SQLFOREIGNKEYS"."PK_NAME", "SYSIBM"."SQLFOREIGNKEYS"."PKTABLE_SCHEM", "SYSIBM"."SQLFOREIGNKEYS"."PKTABLE_NAME", "SYSIBM"."SQLFOREIGNKEYS"."PKCOLUMN_NAME" 
FROM "SYSCAT"."TABLES" INNER JOIN "SYSIBM"."SQLFOREIGNKEYS" ON "SYSCAT"."TABLES"."TABNAME" = "SYSIBM"."SQLFOREIGNKEYS"."PKTABLE_NAME" 
WHERE "SYSCAT"."TABLES"."TYPE" = ? AND "SYSCAT"."TABLES"."TABSCHEMA" = ? AND "SYSIBM"."SQLFOREIGNKEYS"."FKTABLE_NAME" = ? ORDER BY "SYSCAT"."TABLES"."TABNAME"
```

 This will help solve the autoload issue for SAMPLE database.

This implementation is only on LUW server for now.

The code change is implemented manually as the PR needs to be rebased.

This is an important change and hence the change was implemented. We thank you for your contribution @mdobrzanski 

Thanks

**Comment by amukherjee28** [comment]
Changing the query for get_foreign_keys  to check where the foreign key table is of type table helps to distinguish alias from table.

Current new query

```
SELECT "SYSIBM"."SQLFOREIGNKEYS"."FK_NAME", "SYSIBM"."SQLFOREIGNKEYS"."FKTABLE_SCHEM", "SYSIBM"."SQLFOREIGNKEYS"."FKTABLE_NAME", "SYSIBM"."SQLFOREIGNKEYS"."FKCOLUMN_NAME", "SYSIBM"."SQLFOREIGNKEYS"."PK_NAME", "SYSIBM"."SQLFOREIGNKEYS"."PKTABLE_SCHEM", "SYSIBM"."SQLFOREIGNKEYS"."PKTABLE_NAME", "SYSIBM"."SQLFOREIGNKEYS"."PKCOLUMN_NAME" 
FROM "SYSCAT"."TABLES" INNER JOIN "SYSIBM"."SQLFOREIGNKEYS" ON "SYSCAT"."TABLES"."TABNAME" = "SYSIBM"."SQLFOREIGNKEYS"."PKTABLE_NAME" 
WHERE "SYSCAT"."TABLES"."TYPE" = ? AND "SYSCAT"."TABLES"."TABSCHEMA" = ? AND "SYSIBM"."SQLFOREIGNKEYS"."FKTABLE_NAME" = ? ORDER BY "SYSCAT"."TABLES"."TABNAME"
```

 This will help solve the autoload issue for SAMPLE database.

This implementation is only on LUW server for now.

The code change is implemented manually as the PR needs to be rebased.

This is an important change and hence the change was implemented. We thank you for your contribution @mdobrzanski 

Thanks

**Pull request closed without merging**
