### PR TITLE
py3 compatibility

### PR DESCRIPTION
**Pull request by rredburn**
I'd really like to take advantage of sqlalchemy in a Python 3 + DB2 environment as I'm sure others would.  I've taken an initial stab at updating the code.  I unfortunately do not have a full test environment to verify all of the changes across supported systems (LUW, Z, AS400, etc).  Nor do I have a py2 environment on hand to verify these changes do not break compatibility.  Are any of the project maintainers willing to run the SA unit tests across systems and help debug a py2 + py3 compatible release?   str vs. bytes vs. unicode changes are particularly troublesome and I undoubtedly have not found all spots where it has to be handled differently.   

PS.  I'm an IBMer if it matters for contribution purposes (rredburn@us.ibm.com)

### CODE REVIEW

**Comment by rredburn** [comment]
@SabaKauser, @rpriyadh, are you interested in working with me to test and merge these changes to enable ibm_db_sa for py3 users?  You can contact me internal to IBM if private discussion is needed.  I've been using this updated branch in py3.5 applications interacting with LUW DB2 instances successfully.

**Comment by dr-leo** [comment]
@Robert,

As your ibm_dbsa repo has no issue tracker, I take the liberty to
describe here what is likely a bug
somewhere in the tool-chain. Please let mee know any better way to
report a potential issue on your very useful Py3 port. 
 
I work at a client in the public sector using a fairly large data
warehouse based on DB2 10.5.
Locally I use SQLAlchemy 1.0, the latest ibm_db driver for Python and
your ibmdbsa port.

Let me caveat that I am fairly new to sqlalchemy and SQL.
 
I want to do an  CASE expression in a SELECT list returning VARCHAR:

case_expr = case([
    (table.c.somecol == 'Y', 'Yes')],
    else_='No')
s = select([case_expr]).select_from(mytable)

This naturally results in a programming error as
result expressions of a CASE must be typed:

https://www-01.ibm.com/support/knowledgecenter/SSEPGG_9.7.0/com.ibm.db2.luw.sql.ref.doc/doc/r0053561.html


However, casting them to, say, VARCHAR as described in
https://www-01.ibm.com/support/knowledgecenter/SSEPGG_9.7.0/com.ibm.db2.luw.messages.sql.doc/doc/msql00418n.html?lang=en

using sqlalchemy String() type results in the same error:

case_expr = case([
    (table.c.somecol == 'Y', cast('Yes', String(5)))],
    else_=cast('No', String(5)))   

I wonder if there is a bug in ibmdbsa.
Unfortunately, I cannot test this with Py27.
 
Thanks.

Leo


Am 29.01.2016 um 20:57 schrieb Robert Redburn:

**Comment by dr-leo** [comment]
https://github.com/ibmdb/python-ibmdbsa/issues/7 affects this PR as well.

**Comment by bimalkjha** [comment]
Code changes is already merged using other commit. Hence closing it. Thanks.

**Pull request closed without merging**
